[storage]
driver = "overlay"
graphroot = "/var/tmp/$USER/podman"

# Important: if previously using fuse, run podman system reset -f before running

# Applying e.g. --rm to podman run when using overlay sets mountopt volatile on /
# This is undesirable as e.g. Sober and others break when fsync not exhibiting normal behaviour
# Podman ignores fsync=auto/fsync=strict, only disable-volatile stops Podman setting it
# This was a regression with moving from podman create & podman exec to just podman run with --rm
[storage.options]
disable-volatile=true
mount_program = ""
