name: Build and Publish Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Lowercase repo name
        run: echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'
      
      - name: MODERN PODMAN PLS GHA
        uses: redhat-actions/podman-install@v1
        with:
          start-service: 'true'

      - name: Build Image with Buildah
        id: build-img
        uses: redhat-actions/buildah-build@v3
        with:
          image: ${{ env.REPO_LC }}
          tags: latest
          containerfiles: ./Containerfile
          disable-fuse-overlayfs: true
          extra-args: |
            --squash
  
      - name: Push to GHCR
        id: push-img
        uses: redhat-actions/push-to-registry@v3
        with:
          image: ${{ steps.build-img.outputs.image }}
          tags: ${{ steps.build-img.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: |
            --format=oci
            --compression-format=zstd
            --compression-level=7
