name: Build and Publish Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Copy storage conf
        run: |
          mkdir -p /home/runner/.config/containers
          cp ./host/storage.conf /home/runner/.config/containers/storage.conf
          podman system reset -f

      - name: Lowercase repo name
        run: echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Build Image with Buildah
        id: build-img
        uses: redhat-actions/buildah-build@v3
        with:
          image: ${{ env.REPO_LC }}
          tags: latest
          containerfiles: ./Containerfile
          disable-fuse-overlayfs: true
          extra-args: |
            --squash
          labels: |
            uwcs.fng.commit=${{ github.sha }}
  
      - name: Push to GHCR
        id: push-img
        uses: redhat-actions/push-to-registry@v3
        with:
          image: ${{ steps.build-img.outputs.image }}
          tags: ${{ steps.build-img.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: |
            --compression-format=zstd
            --compression-level=7
